# Files distributed to students (.ok & tests/ handled automatically)
fa19\lab\lab09.d: $(MATERIALS_DST)/fa19\lab\lab09/bootstrap.png
fa19\lab\lab09.d: $(MATERIALS_DST)/fa19\lab\lab09/denmark_scores.csv
fa19\lab\lab09.d: $(MATERIALS_DST)/fa19\lab\lab09/happiness_scores.csv
fa19\lab\lab09.d: $(MATERIALS_DST)/fa19\lab\lab09/us_happiness_factors.csv