# Files distributed to students (.ok & tests/ handled automatically)
fa19\lab\lab03.d: $(MATERIALS_DST)/fa19\lab\lab03/world_population.csv
fa19\lab\lab03.d: $(MATERIALS_DST)/fa19\lab\lab03/array_logarithm.jpg
fa19\lab\lab03.d: $(MATERIALS_DST)/fa19\lab\lab03/array_multiplication.jpg
fa19\lab\lab03.d: $(MATERIALS_DST)/fa19\lab\lab03/more_restaurant_bills.csv
fa19\lab\lab03.d: $(MATERIALS_DST)/fa19\lab\lab03/excel_array.jpg
fa19\lab\lab03.d: $(MATERIALS_DST)/fa19\lab\lab03/chaining_method_calls.png
fa19\lab\lab03.d: $(MATERIALS_DST)/fa19\lab\lab03/imdb.csv