# Files distributed to students (.ok & tests/ handled automatically)
fa19\hw\hw05.d: $(MATERIALS_DST)/fa19\hw\hw05/calories_per_minute.csv
fa19\hw\hw05.d: $(MATERIALS_DST)/fa19\hw\hw05/exercise.csv
fa19\hw\hw05.d: $(MATERIALS_DST)/fa19\hw\hw05/deck.csv