# Files distributed to students (.ok & tests/ handled automatically)
fa19\hw\hw03.d: $(MATERIALS_DST)/fa19\hw\hw03/unemployment.csv
fa19\hw\hw03.d: $(MATERIALS_DST)/fa19\hw\hw03/nst-est2016-alldata.csv
fa19\hw\hw03.d: $(MATERIALS_DST)/fa19\hw\hw03/scatter.png
fa19\hw\hw03.d: $(MATERIALS_DST)/fa19\hw\hw03/var1.png
fa19\hw\hw03.d: $(MATERIALS_DST)/fa19\hw\hw03/var2.png
fa19\hw\hw03.d: $(MATERIALS_DST)/fa19\hw\hw03/boston.csv
fa19\hw\hw03.d: $(MATERIALS_DST)/fa19\hw\hw03/manila.csv