# Files distributed to students (.ok & tests/ handled automatically)
fa19\hw\hw02.d: $(MATERIALS_DST)/fa19\hw\hw02/president_births.csv
fa19\hw\hw02.d: $(MATERIALS_DST)/fa19\hw\hw02/temperatures.csv
fa19\hw\hw02.d: $(MATERIALS_DST)/fa19\hw\hw02/world_population.csv
fa19\hw\hw02.d: $(MATERIALS_DST)/fa19\hw\hw02/array_diff.png
fa19\hw\hw02.d: $(MATERIALS_DST)/fa19\hw\hw02/array_cumsum.png
fa19\hw\hw02.d: $(MATERIALS_DST)/fa19\hw\hw02/old_faithful.csv
fa19\hw\hw02.d: $(MATERIALS_DST)/fa19\hw\hw02/inventory.csv
fa19\hw\hw02.d: $(MATERIALS_DST)/fa19\hw\hw02/sales.csv