# Files distributed to students (.ok & tests/ handled automatically)
fa19\hw\hw10.d: $(MATERIALS_DST)/fa19\hw\hw10/restaurant_inspection_scores.csv
fa19\hw\hw10.d: $(MATERIALS_DST)/fa19\hw\hw10/united_summer2015.csv