# Files distributed to students (.ok & tests/ handled automatically)
fa19\lab\lab02.d: $(MATERIALS_DST)/fa19\lab\lab02/world_population.csv
fa19\lab\lab02.d: $(MATERIALS_DST)/fa19\lab\lab02/imdb.csv
fa19\lab\lab02.d: $(MATERIALS_DST)/fa19\lab\lab02/farmers_markets.csv
fa19\lab\lab02.d: $(MATERIALS_DST)/fa19\lab\lab02/statement.png