# Files distributed to students (.ok & tests/ handled automatically)
fa19\lab\lab04.d: $(MATERIALS_DST)/fa19\lab\lab04/raw_compensation.csv
fa19\lab\lab04.d: $(MATERIALS_DST)/fa19\lab\lab04/movies_by_year.csv
fa19\lab\lab04.d: $(MATERIALS_DST)/fa19\lab\lab04/apply.png