# Files distributed to students (.ok & tests/ handled automatically)
fa19\lab\lab01.d: $(MATERIALS_DST)/fa19\lab\lab01/error.jpg
fa19\lab\lab01.d: $(MATERIALS_DST)/fa19\lab\lab01/numberline_0.png
fa19\lab\lab01.d: $(MATERIALS_DST)/fa19\lab\lab01/numberline_1.png
fa19\lab\lab01.d: $(MATERIALS_DST)/fa19\lab\lab01/map.jpg