# Files distributed to students (.ok & tests/ handled automatically)
fa19\hw\hw04.d: $(MATERIALS_DST)/fa19\hw\hw04/causes_of_death.csv.zip
fa19\hw\hw04.d: $(MATERIALS_DST)/fa19\hw\hw04/abbreviations.csv
fa19\hw\hw04.d: $(MATERIALS_DST)/fa19\hw\hw04/faculty.csv
fa19\hw\hw04.d: $(MATERIALS_DST)/fa19\hw\hw04/berkeley_faculty.csv