# Files distributed to students (.ok & tests/ handled automatically)
fa19\lab\lab05.d: $(MATERIALS_DST)/fa19\lab\lab05/Austen_PrideAndPrejudice.txt
fa19\lab\lab05.d: $(MATERIALS_DST)/fa19\lab\lab05/player_data.csv
fa19\lab\lab05.d: $(MATERIALS_DST)/fa19\lab\lab05/salary_data.csv
fa19\lab\lab05.d: $(MATERIALS_DST)/fa19\lab\lab05/small_srswor_salary.csv
fa19\lab\lab05.d: $(MATERIALS_DST)/fa19\lab\lab05/large_srswor_salary.csv
fa19\lab\lab05.d: $(MATERIALS_DST)/fa19\lab\lab05/comparisons.png
fa19\lab\lab05.d: $(MATERIALS_DST)/fa19\lab\lab05/nacho_reactions.png