# Files distributed to students (.ok & tests/ handled automatically)
fa19\hw\hw12.d: $(MATERIALS_DST)/fa19\hw\hw12/triple_vertical.csv
fa19\hw\hw12.d: $(MATERIALS_DST)/fa19\hw\hw12/btc.csv
fa19\hw\hw12.d: $(MATERIALS_DST)/fa19\hw\hw12/eth.csv
fa19\hw\hw12.d: $(MATERIALS_DST)/fa19\hw\hw12/spreads.csv